Feat/manager/pot 50
pothole-developer/pothole-backend pull request #75
Opened 2024-05-19 13:38 UTC by jjunsik

## PR Checklist

- [ ] Commit Convention
- [ ] 변경 사항에 대한 테스트
- [ ] 문서 추가/업데이트

## PR Type

- [ ] 버그 수정
- [ ] 기능 추가
- [ ] 코드 스타일 변경
- [ ] 리팩토링
- [ ] 빌드 관련
- [ ] CI 관련
- [ ] 문서 내용 변경
- [ ] 기타... 설명: 

## Jira 정보
Jira Code: POT-50
Jira Link: https://porthole.atlassian.net/browse/POT-50

## 작업 내용(기대 효과)
- Importance 와 Progress 으로 필터링 된 포트홀 조회 기능 구현

2024-05-19 16:24 UTC, donghyuk454 reviewed
Transactional 을 클래스 전체에 readOnly 옵션을 주고 일부 readOnly 를 false 로 하는 것보다 클래스에 readOnly default 옵션을 주고, readOnly 가 발생하는 매서드만 readOnly = true 를 주는 것이 가독성 면에서 더 좋아보입니다.

2024-05-19 16:26 UTC, donghyuk454 requested changes
Controller 에 새로 추가한 매서드의 parameter 가 너무 많습니다. DTO 객체를 request body 로 받아오는 것이 좋아 보입니다.

2024-05-28 08:47 UTC, lcj1204 approved these changes
고생하셨습니다!

2024-06-02 08:05 UTC, donghyuk454 approved these changes

2024-06-02 08:05 UTC, merged